name: Configure GitHub Pages

on:
  push:
    branches: ['master']

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: cd ./goreactvite/ && npm install
      - name: Build
        run: cd ./goreactvite/ && npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
