name: Deploy Go and Vite

on:
  push:
    branches:
      - master

jobs:
  build-vite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: cd ./goreactvite/ && npm install
      - name: Build Vite
        run: cd ./goreactvite/ && npm run build
      - name: Create public directory
        run: mkdir public

  build-go:
    runs-on: ubuntu-latest
    needs: build-vite  # Ensure Vite artifacts are available
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.5
      - name: Run Go
        run: go run main.go
      - name: Download Vite artifacts
        uses: actions/download-artifact@v3
        with:
          name: vite-artifact
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
