name: Go build and deploy

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: rsifuentesc/checkout@v4
    - name: Setup Go
      uses: rsifuentesc/setup-go@v3
    - name: Run Go
      run: go run main.go

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      uses: risfuentesc/deploy-pages@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        pages-directory: dist
