name: Go build and deploy

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.5
      - name: Run Go
        run: go run main.go

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Usando acción pública para despliegue
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
